= THE A-MAZE-ING PROJECT!

:sectnum!:
== Introduction
This repository contains source code, compiling tools and few extras for the Maze Project (INF103 course, 1st year at Télécom Paris).
Please read this README, at least the *Getting started* section in order to learn how to use the interface.

==== Motivation
The project was designed to understand and get used to JAVA programming by implementing the Dijkstra algorithm.
The algorithm is used here as a tool for solving mazes.

==== What I achieved
After finished with the project requirements, which was done by mid-December, I wanted to go further and propose additional features.

Unfortunately I ran short of time. Consequently the graphical interface is limited to a display of the maze, the user can interact only via
a prompt. Nevertheless this interface provides many tools which I will detail further on.

I was also planning on adding altitude. I adapted the format of files in consequence but the graph does not take it into account. I also made
it easy to develop new types of boxes with customized behaviour. This, nevertheless is still exprimental and calls for some modifications in
the implementation of Maze class.

==== Global architecture
The global architecture has undergone many changes since the creation of the project. The red line was to come up with with an easily
modifiable implementation. It is divided in 4 packages :

* *dijkstra* contains all necessary interfaces and classes for implementing the Dijkstra algorithm
* *maze* implements the graph via the class Maze and proposes an interface for creating a user interface
* *ui* provides a prompt interface with window in parallel drawing the maze
* *graphics* provides the classes for drawing

Sample classes can be found for implementing new objects with customized behaviours. Once coded, it has to be linked :

* *Box* : for linking a box, the only thing to do is to add an entry in the static method `newBox` in abstract class `Box`
* *CommandInterface* : for linking a command to the prompt interface, an entry has to be added in the `constructor` of class `PromptInterface`

== Compilation
This project was not made in Eclipse, however you will find, at the root of the repository, a Makefile. To compile, please follow the steps :

. `make clean` to remove every .class file and force `make` to recompile
. `make` to compile
. Launch the app : `java -jar app.jar`

== Getting started with the PromptInterface
It is now time to explain how to use the _PromptInterface_.

=== Understanding the basics

==== Command queues and stacks

The interface is basically two-step : 

. *Enter* commands : this can be done via _direct user input_, _script loader_, or _iteration loops_.
. *Execute* these commands, remembering that some of them can get back to the first step.

Each input method has a specific container in which it pushes the commands :
* _direct user input_ pushes to `main queue`
* _script loader_ pushes to `script stack`
* _iteration loops_ pushes to `iteration queue`

The interface will execute commands, giving priority to the `iteration queue`, the `main queue` then the `script stack` until both are empty.
When it is, it requests a _direct user input_, visualized by a `>>>` in the prompt.

==== Parsing

Whenever a command is pulled from a queue, it is formatted so that long blanks are removed.

When the interface executes a command it is required to parse it first by default. Some commands, like `times`, shall implement their own
parser due to technical issues. The interface parser will replace variable labels by their values, and will process randomization.

Then the command is passed to the `CommandInterface` via a call to its method `run`, which parse it specifically following its behaviour.

==== Exception management

During the execution, many exceptions can be raised, all the more with a prompt interface not restricting the _user input_. The method
`executeCommand` catches every exception, indicates it to the user, then continue. It does not cancel every action already made by the
command, such as defining variables or pushing commands.

=== Syntax of a command
The syntax is very simple. For a basic command, it goes like `<command name> (arguments)`.
Integer arguments such as positions or coordinates can be randomized by typing `random <min> <max>`.

Not many commands have a fixed number of arguments, they can have differents usages or wait for arguments depending on previouly passed ones.

Note that if, in certain cases, if not enough arguments were passed, the command may deduce default values, `0` for `integers` for instance.

===== Get help about a command
`help` will show a list of commands and `usage <command name>` will show how to use a command.

=== Variables
The interface can record variables. A _variable_ consists of a *label* and a *value*, both are `String` objects.

To define a variable, you can use the `var` command : `var label = value`.

To use a variable in a command, you write `$label` instead of an arguments.

To display a list of every variable, type `variables`.

===== Special variables
Some variables can be useful everytime, such as maze dimensions. In order to make it easier, not having to demand for it each you want it, the interface defines several _special variables_, these are `width`, `height` and `area`.

These are updated each time the maze is modified and can not be overriden.

=== Iterations
The `times` command allows you to _iterate a command_, the syntax is `times counter <first> <last> <command>`
The `counter` is increased from `first` to `last` (excluded) and can be used as an integer variable in the `command`.

Be careful however, this feature in currently experimental.
`times` implements its own parser due to technical issues such as conflicts between interface variables and the `counter`.
The parser distinguishes the iteration parameters the command following. In the iteration parameters, it will parse `first` and `last` and
can search for interface variables. In the command, it will first replace every occurence of `$counter`, then push the command to the 
`iteration queue`, so that the default parser can be called, except if this is also a `times`.

Let's give an example : `times x 0 $width times y 0 $height addbox $x $y empty`

For the first `times`, x is the `counter`. The `times` parser will fetch `$width` which is indeed an interface variable since it is a _special
variable_. Then it will replace every occurrence of `$x`, so the command iterated the first time will be `times y 0 $height addbox 0 $y 
empty`.


=== Scripts
One of the main feature is _scripting_. It allows one to execute several commands without having to enter them manually.

==== Show a script
The command `showscript <script name>` will display the given script.

There are two sections, one detailing the _variables_ to provide when loading the script, and the second the _actual commands_.

==== Load a script
To load a script, you must enter `script <script name> (arguments)`.
The arguments are the ones showed by `showscript`, in that order.

When a script is loaded, it is parsed and all the script variables are replaced.
If some undefined variables are encountered, the loader will assume these are already defined in the interface. 
For example you can use height, width or area. You can even override them locally in the script.

When loading a script, the commands are placed in the `script stack`, meaning that when `times` is used in script,
it will fill the `iteration queue`, which has a higher priority, so as to get a consistent flow. 
Believe me, an inconsistent flow can result in very undefined behviors...

A script within in script will pile up, so the flow is still consistent.

==== Write your own scripts
The syntax of scripts is pretty much the same as the interface syntax.
You can however use variables that are to define by the user, by using the syntax `$label;`. 
This will require the user to provide the value of `label` when calling the script. 

Such variables remain defined in the interface even after the script was executed.

==== Record scripts
You can also record a list of commands in a script. For starting to record, simply use the `record` command. 
When finished, use `savescript <script name>` to stop recording and save the commands in a script.
You might want to avoid some commands to be recorded. 

For instance, you might to display the maze while recording, for checking purpose, so it is not desired in the final script. 
You can do so by starting your command by `*`, for example `* display`.

Note that the parser is called before recording, so you can not use variables in recorded scripts except for iterations `counters`.

==== Some useful scripts
I thought some scripts might prove useful to get started. They can be found in the scripts/

* _randommaze.mzs <width> <height>_ creates a new random maze made of walls and empty boxes.
* _.mzs <file> <xRoot> <yRoot> <xEnd> <yEnd>_ opens the maze file and traces path from the given root to the given end.
* _.mzs <xRoot> <yRoot> <xEnd> <yEnd>_ traces path from the given root to the given end.

=== Compatibility Mode
The project gave a format of file which I decided to change regarding my implementation.
My format is not easily editable manually, so I made a compatibility mode which old-formatted mazes to be opened. 
To use it, simply add `compatibility` to the command `open` or `save`.

Note that using `write` in compatibility mode can result in a loss of information. First you will lose every MARKED flag when saving. 
Second, any box type other than Wall or Empty will not be saved and will appear as null boxes.

=== Example
Let's say we have maze saved in an old-formatted file, named maze.map in maps/ . This file indicates the position of root and end.
Once the interface launched, we can load the script project_assess.mzs with arguments maps/maze.map and maps/maze_solved.map :
`script scripts/project_assess.mzs maps/maze.map maps/maze_solved.map`

This script uses the compatibility mode to read and write the maze, so that you can run tests more easily.

=== Need help ?
In case you have questions about the interface or want to report a bug, you can send a mail to 
mailto:florian.tarazona@telecom-paris.fr[Florian Tarazona].

== Features to add

Here is a list of features that could be implemented yet :

* Run scripts when launching `app.jar` via the program arguments
* Add z coordinate (we can use HashMap instead of matrix to allow several boxes on same (x, y), such as bridges)
* For the moment, having setters for coordinates in Box is used by maze when adding columns and rows, but it breaks encapsulation in some
 way. It shall be removed.
* Adding tests for scripts in the interface would allow making real mini-programs.
* As integer values in the current format are limited to 254, it is not possible to make big maps. It would possible to consider agglomerate
 chunks within an object Map which would have the same interface as Maze.
* Create a graphical interface with graphical input.
* Just like in a game we could imagine some boxes could be triggered, hence modify their own behaviour, depending on the position of other
 boxes.
